MODEL:
    NUM_CLASSES: 11
    BACKBONE:
        NAME: 'basic'
        PRETRAINED: False
        OUT_CHANNELS: [128, 256, 128, 128, 64, 64]
        INPUT_CHANNELS: 3
    PRIORS:
        MAX_SIZES: [[38, 38], [90, 90], [153, 153], [207, 207], [264, 264], [312, 312]]
        MIN_SIZES: [[16, 16], [38, 38], [90, 90], [153, 153], [207, 207], [264, 264]]
    THRESHOLD: 0.45
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("mnist_detection_train", "mnist_detection_val")
    TEST: ("mnist_detection_val", )
SOLVER:
    MAX_ITER: 15000
    GAMMA: 0.1
    BATCH_SIZE: 32
    

OUTPUT_DIR: 'outputs/improved_basic'
DATASET_DIR: "/work/datasets"
