MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet_experimental'
        PRETRAINED: True
        OUT_CHANNELS: [1024, 512, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
    PRIORS:
        ASPECT_RATIOS: [[2,3], [2, 5], [3, 5], [2, 4], [2,3], [2,4]]
        MIN_SIZES: [[21, 21], [45, 45], [99, 99], [153, 153], [207, 207], [261, 261]]
        MAX_SIZES: [[45, 45], [99, 99], [153, 153], [207, 207], [261, 261], [315, 315]]
        BOXES_PER_LOCATION: [6, 6, 6, 6, 6, 6]

INPUT:
    IMAGE_SIZE: [300, 300]
    PIXEL_STD: [0.229, 0.224, 0.225] 
    PIXEL_MEAN: [0.485, 0.456, 0.406]

DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 30000
    GAMMA: 0.1
    BATCH_SIZE: 22
    MOMENTUM: 0.9
    LR: 2e-3
EVAL_STEP: 2000
MODEL_SAVE_STEP: 2000
OUTPUT_DIR: 'outputs/aspect_ratios_smaller_sizes2_widenet_moreboxes'
DATASET_DIR: "/work/datasets"