MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'SSD300'
        PRETRAINED: True
        OUT_CHANNELS: [1024, 512, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
    PRIORS:
        BOXES_PER_LOCATION: [4, 6, 10, 10, 10, 10]
        MIN_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        ASPECT_RATIOS: [[2], [2, 3], [2, 3,4,5], [2, 3, 4, 5], [2,3,4,5], [2,3,4,5]]

INPUT:
    IMAGE_SIZE: [300, 300]
    PIXEL_STD: [0.229, 0.224, 0.225] 
    PIXEL_MEAN: [0.485, 0.456, 0.406]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 10000
    GAMMA: 0.1
    BATCH_SIZE: 2
    MOMENTUM: 0.9
    LR: 2e-3
    SCHEDULER:
        MILESTONES: [10000, 15000]
        GAMMA: 0.1
EVAL_STEP: 1000
MODEL_SAVE_STEP: 1000
OUTPUT_DIR: 'outputs/SSD300'
DATASET_DIR: "/work/datasets"
SOFT_NMS: False