MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet_50'
        PRETRAINED: True
        OUT_CHANNELS: [1024, 512, 512, 256, 256, 256] #[128, 256, 128, 128, 64, 64]  #[512, 1024, 512, 256, 256, 256] 
        INPUT_CHANNELS: 3
    PRIORS:
        FEATURE_MAPS: [[30, 40], [15, 20], [8, 10], [4, 5], [2, 3], [1, 1]] #[[38, 38], [19, 19], [10, 10], [5, 5], [3, 3], [1, 1]] 
        
        ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
        BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
        MAX_SIZES: [[38, 38], [90, 90], [153, 153], [207, 207], [264, 264], [312, 312]]
        MIN_SIZES: [[16, 16], [38, 38], [90, 90], [153, 153], [207, 207], [264, 264]]
        
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 5000
    GAMMA: 0.1
    BATCH_SIZE: 5
    LR: 2e-3
OUTPUT_DIR: 'outputs/rdd_2020_resnet'
DATASET_DIR: "/work/datasets"