MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet_experimental'
        PRETRAINED: True
        OUT_CHANNELS: [1024, 512, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
        
INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 15000
    GAMMA: 0.1
    BATCH_SIZE: 16
    MOMENTUM: 0.9
    LR: 2e-3
EVAL_STEP: 5000
MODEL_SAVE_STEP: 2500
OUTPUT_DIR: 'outputs/rdd_2020_resnet_experimental-custom'
DATASET_DIR: "/work/datasets"