MODEL:
    NUM_CLASSES: 5
    BACKBONE:
        NAME: 'resnet_experimental'
        PRETRAINED: True
        OUT_CHANNELS: [1024, 512, 512, 256, 256, 256]
        INPUT_CHANNELS: 3
    PRIORS:
        BOXES_PER_LOCATION: [4, 6, 10, 10, 10, 10]
        MIN_SIZES: [[30, 30], [60, 60], [111, 111], [162, 162], [213, 213], [264, 264]]
        MAX_SIZES: [[60, 60], [111, 111], [162, 162], [213, 213], [264, 264], [315, 315]]
        ASPECT_RATIOS: [[2], [2, 3], [2, 3,4,5], [2, 3, 4, 5], [2,3,4,5], [2,3,4,5]]

INPUT:
    IMAGE_SIZE: [300, 300]
DATASETS:
    TRAIN: ("rdd2020_train",)
    TEST: ("rdd2020_val", )
SOLVER:
    MAX_ITER: 30000
    GAMMA: 0.1
    BATCH_SIZE: 16
    MOMENTUM: 0.9
    LR: 2e-3
EVAL_STEP: 500
MODEL_SAVE_STEP: 500
OUTPUT_DIR: 'outputs/wide_resnet-x-600-moreboxes'
DATASET_DIR: "/work/datasets"